show dbs
use demo
db.createCollection("demo1")
db.demo1.insert([
{
"name":"bhoutik",
"age":25,
"location":"santacruz",
"skill":"mongo",
"education":"masters"
},
{
"name":"ramesh",
"age":28,
"location":"malad",
"skill":"java",
"education":"undergrad"
},
{
"name":"suresh",
"age":31,
"location":"khar",
"skill":"mongo",
"education":"undergrad"
},
{
"name":"paul",
"age":38,
"location":"bandra",
"skill":"python",
"education":"masters"
},
{
"name":"wayne",
"age":41,
"location":"borivali",
"skill":"java",
"education":"undergrad"
},
{
"name":"vidic",
"age":19,
"location":"santacruz",
"skill":"python",
"education":"masters"
}])
db.demo1.insert({"name":"van der sar","age":29,"location":"goregaon","skill":"javascript","education":"undergrad"})
db.demo1.find()
db.demo1.find({"name":"paul"})
db.demo1.find({"age":{$gt:35}})
db.demo1.find({"name":"bhoutik","age":25})
db.demo1.find({$or:[{"name":"bhoutikk"},{"age":25}]})
db.demo1.find({"name":"bhoutik",$or:[{"age":26},{"location":"santacruz"}]})

db.demo1.update({"name":"bhoutik"},{$set:{"name":"legend"}},{multi:true})
db.demo1.update({"name":"legend"},{$set:{"name":"bhoutik"}})
db.createCollection("demo3")
db.demo3.insert({"name":"gesd","age":26})
db.demo3.find()
db.demo3.remove({"age":26})
